### PR TITLE
Balanced some things and fixed some coding things

### PR DESCRIPTION
**Pull request by DrEthan77**
The description in the first commit has the changes

### CODE REVIEW

**Review by CAPS123987 — CHANGES_REQUESTED** [review]
remove the Small miscalculation commit, because you changed it back

**Comment by DrEthan77** [comment]
Lol oops, let me fix that real quick

**Comment by DrEthan77** [comment]
Done

**Review by CAPS123987 — APPROVED** [review]

**Comment by CAPS123987** [comment]
thank you

**Comment by DrEthan77** [comment]
No problem, I would like to volunteer to help with this as having more options for reactors that require maintenance is much better than how most plugins generate energy currently.

**Pull request merged**
