### PR TITLE
Formatting plus a couple more balancing tweaks

### PR DESCRIPTION
**Pull request by DrEthan77**
Description in commits.

### CODE REVIEW

**Review by CAPS123987 — CHANGES_REQUESTED** [review]
Cool Thanks, just please set coolantTime that the coolant will be eaten every 4 ticks (2s)

**Comment by DrEthan77** [comment]
Hmmm, I still think 4 ticks is too low that's less than 1/10th of the base reactor, I think it should at least be 8 ticks, what do you think about that?

**Comment by CAPS123987** [comment]
Ok cool

**Comment by DrEthan77** [comment]
Done

**Review by CAPS123987 — APPROVED** [review]

**Pull request merged**
