### PR TITLE
Added fallout config

### PR DESCRIPTION
**Pull request by DrEthan77**
Description in commits, with large fallout disabled it will only put a radius 12 circle around where the reactor was.

### CODE REVIEW

**Comment by CAPS123987** [comment]
I'm sorry but I don't like the option to have small fallout, if you could remove it it would be nice, also if you can please change the particle to be _Particle.REDSTONE,new DustOptions(Color.GREEN,1)_ (just set it's particle to this)

**Comment by DrEthan77** [comment]
So you would rather have only no fallout or all the fallout? I added small fallout because the large fallout lagged and then crashed the server, but I still like the idea of having some fallout when the reactor explodes.

**Comment by DrEthan77** [comment]
How about if I change it so by default the large fallout is on but I still keep the option for turning off the fallout and the small fallout?

**Comment by CAPS123987** [comment]
sorry for late reply, yes that would be better

**Comment by CAPS123987** [comment]
Good now please change the particles and I'l merge it

**Comment by DrEthan77** [comment]
What particles? I haven't touched/changed any particles?

**Comment by CAPS123987** [comment]
Set particles to
Particle.REDSTONE,new DustOptions(Color.GREEN,1)

**Comment by CAPS123987** [comment]
1 weeks till I close this PR

**Comment by DrEthan77** [comment]
Well I've done what I wanted to do xD, you asking me to do other random stuff not related to what I was changing is a little weird.

**Comment by CAPS123987** [comment]
Well it is related but ok. I'll do it

**Pull request merged**
